### ISSUE TITLE
Cannot load extension on Ubuntu 16.04

### ISSUE THREAD

**Issue by edigonzales** [strk/fineltra#6]
The extension cannot be load on a fresh Ubuntu 16.04:

`ERROR:  could not load library "/usr/lib/postgresql/9.5/lib/fineltra-0.0.so": /usr/lib/postgresql/9.5/lib/fineltra-0.0.so: undefined symbol: geod_polygon_addpoint`

**Comment by strk** [comment]
How did you build fineltra ? That error might mean that you built fineltra against a libproj version equal or greater than 4.9.0 while you're attempting to load the resulting fineltra-0.0.so on a machine in which libproj version is older. Can this be the case ?

Also, which version of liblwgeom did you build fineltra against ?

See https://github.com/postgis/postgis/commit/e0d2f255eaaf3bd856652a2c76771f9dbb9809af

**Comment by strk** [comment]
It may be a good idea to port Fineltra to use the `librttpo` library instead of `liblwgeom`, which is prone to frequent ABI breakages http://strk.keybit.net/projects/rttopo/index.html

**Comment by strk** [comment]
If I read that commit correctly, the geod_polygon_addpoint symbol was introduced in liblwgeom library version 2.2.0, but is only present when the library is built against proj >= 4.9.0

**Comment by edigonzales** [comment]
`./autogen.sh`
`./configure`
`make install`

All needed dependencies are installed from ubuntu packages. Versions seems to be fine, e.g. libwgeom-2.2-5:
`Depends: libc6 (>= 2.14), libgeos-c1v5 (>= 3.5.0), libjson-c2 (>= 0.10), libproj9 (>= 4.9.0), libsfcgal1 (>= 1.1.0)`

Would it be still possible the libwgeom is not build against proj 4.9?

**Comment by strk** [comment]
If the package is not broken, I'd think it was built against proj 4.9.
You could check with `nm` if the `geod_polygon_addpoint` symbol is present in the liblwgeom.so file.

But Fineltra links liblwgeom _statically_ so if it was built on a different system with an older proj4 it would not have that symbol. When using a mix of statically and dynamically linked libraries there could be symbol clashes so that code which expects to find a symbol ends up calling other code in which such symbol is not found. Not easy to tell what's going on without taking a closer (on-system) look.

Or you could try building fineltra again on the new system (or, would probably be even better) build it _dynamically_ rather than statically. The current build scripts link it statically as the official PostGIS builds are also static, but it looks like distributions are using dynamic linking for PostGIS instead.

This may change in the future, as clients start to move from liblwgeom to librttopo  (https://strk.kbt.io/projects/rttopo/)

**Comment by edigonzales** [comment]
I was able to solve the issue:

`./configure --with-liblwgeom=/usr/lib/liblwgeom.so`

**Comment by strk** [comment]
thanks for confirming

**Comment by andreasneumann** [comment]
hm - just ran into the same issue on CentOS 7.

@edigonzales your hint with --with-liblwgeom=/usr/local/lib/liblwgeom.so also helped in my case.
