### ISSUE TITLE
make: *** No rule to make target 'install'

### ISSUE THREAD

**Issue by 3nids** [strk/fineltra#7]
I hit `make: *** No rule to make target 'install'.  Stop.` whenever I do `make install`

Running on Ubuntu, previous steps were fine.

Any idea?

**Comment by 3nids** [comment]
@edigonzales any idea?

**Comment by edigonzales** [comment]
This is from my shell script for installing some fossgis stuff:

`# ST_Fineltra`
`apt-get install liblwgeom-dev`
`cd ~`
`git clone https://github.com/strk/fineltra.git ~/sources/fineltra`
`cd ~/sources/fineltra`
`./autogen.sh`
`./configure --with-liblwgeom=/usr/lib/liblwgeom.so`
`make install`

There are a lot of "apt-gets" before for all the other stuff. 

It worked on a 16.04 version and since there are no commits since a year I should still work.

**Comment by 3nids** [comment]
Thanks for your feedback.
It's strange since I had no dependency issues.
It would rather be an issue on Make side.

**Comment by edigonzales** [comment]
Which Ubuntu version?

**Comment by 3nids** [comment]
16.04, server. After a bit of googling, I will try to install build-essential and try again. Will let you know.

**Comment by strk** [comment]
@3nids `make: *** No rule to make target 'install'. Stop.` usually is due to a lack of `./configure` step

**Comment by 3nids** [comment]
Sorry, was missing a library, I did not read carefully the output of confiure.
Sorry for the noise and thanks for your time.
